name: C/C++ CI

on:
  push:
  pull_request:

jobs:
  bogus-setup:
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix: 
        os: [ubuntu-18.04, ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2
    - run: cat /etc/os-release
  
  build-and-setup:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    
    - name: make
      run: make
      
    - name: move binaries
      run: |
        mkdir upload
        mv ./CASBACnetStackCompileTest ./upload/
    
    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: binary
        path: upload
    
  access-artifact:
    needs: build-and-setup
    runs-on: ubuntu-latest
    steps:
    - name: download artifact
      uses: actions/download-artifact@v2
      with: 
        name: binary
        path: ./test-download/
    
        
