name: C/C++ CI

on:
  push:
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
  
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: make
      run: make
      
    - name: move binaries
      run: |
        mkdir upload
        mv ./CASBACnetStackCompileTest ./upload/
    
    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: binary
        path: upload
    
  access-artifact:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: download artifact
      uses: actions/download-artifact@v2
      with: 
        name: binary
        path: ./test-download/
    
        
